name: Main Flow

env:
  APPLICATION_NAME: "Print Variables"
  DOCKER_TAG: ${{ github.REPOSITORY }}:${{ github.GITHUB_SHA }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean build

    - name: Print Variables
      run: |
        echo "GitHub Repository       : ${{ github.GITHUB_REPOSITORY }}"
        echo "GitHub Repository Name  : ${{ github.GITHUB_REPOSITORY_NAME }}"
        echo "GitHub Repository Owner : ${{ github.GITHUB_REPOSITORY_OWNER }}"
        echo "GitHub Git SHA 1        : ${{ github.SHA }}"
        echo "GitHub Git SHA 2        : ${{ github.GITHUB_SHA }}"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag print-variables:$(date +%s)
