name: Main Flow

env:
  APPLICATION_NAME: "Print Variables"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Variables
        run: |
          echo "GitHub Repository         : ${{ github.REPOSITORY }}"
          echo "GitHub Repository Owner   : ${{ github.REPOSITORY_OWNER }}"
          echo "GitHub Repository Name    : ${{ github.event.repository.name }}"
          echo "GitHub Git SHA            : ${{ github.SHA }}"
          echo "GitHub DOCKER TAG Current : ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.SHA }}"
          echo "GitHub DOCKER TAG Latest  : ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}"

      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}, ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.SHA }}
          labels: ${{ steps.meta.outputs.labels }}