name: Main Flow

env:
  APPLICATION_NAME: "Print Variables"
  DOCKERHUB_ACCOUNT: alexanderoleynik
  DOCKER_TAG: "$DOCKERHUB_ACCOUNT/${{ github.event.repository.name }}:${{ github.SHA }}"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build

      - name: Print Variables
        run: |
          echo "GitHub Repository         : ${{ github.REPOSITORY }}"
          echo "GitHub Repository Name 1  : ${{ github.REPOSITORY_NAME }}"
          echo "GitHub Repository Name 2  : ${{ github.event.repository.name }}"
          echo "GitHub Repository Owner   : ${{ github.REPOSITORY_OWNER }}"
          echo "GitHub Git SHA            : ${{ github.SHA }}"
          echo "GitHub DOCKER TAG         : $env.DOCKER_TAG"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $env.DOCKER_TAG
